"""
fake_claims.py — AquaFair
Owner: C

The full demo set as CLAIM dicts — 32 farms across four command areas.

⚠ DO NOT HAND-EDIT THESE NUMBERS.
They were GENERATED by running the real engine:

    from generate import demo_farms
    from farm_agent import build_claims
    from constants import WEATHER_STATES
    build_claims(demo_farms(), WEATHER_STATES["normal"])

An earlier hand-typed version drifted badly — paddy Ky was 1.25 when
constants said 1.35, and water volumes were 6-48% low because they had
been worked out at a 7-day cycle instead of 4. Every number on the
dashboard would have jumped at merge and looked like a rendering bug.

If constants.py or the demo spec changes, REGENERATE rather than patch.
Run `python3 fake_claims.py` — it compares itself against the live
engine and prints the correct values if they have drifted.

WHAT THIS IS FOR
The pipeline does not need it. app.py builds claims from demo_farms()
through farm_agent, so the live numbers are always the engine's own.
This file is a fixed reference for reading the CLAIM shape and for
tests that want stable input.

Rows are ordered HEAD TO TAIL within each source, matching
distance_from_head_m — the order impact.head_to_tail_split() serves
them in, so the current-practice baseline can be read straight off
this file.

Rows are ordered HEAD TO TAIL within each source, matching
distance_from_head_m — the order impact.head_to_tail_split() serves
them in, so the current-practice baseline reads straight off this file.

⚠ NEVER ALLOCATE ACROSS THE WHOLE LIST.
Farms belong to one tank or canal and never compete across them —
Tank A's water does not reach Tank B's farms, and no WUA has the
authority to move it. Use CLAIMS_BY_SOURCE, or filter on source_id.
Pooling all 32 would also silently invert the impact comparison,
because a canal's sugarcane would outbid a village tank's ragi.

F001-F004 (T01, Periya Eri) are the four farms the demo is rehearsed
on. The canal farms are much larger, which is what gives the Impact
panel a real smallholder-versus-large comparison.

Values are for the NORMAL scenario: ETo 5.0 mm/day, no rain, 4-day
cycle. Drought and rain produce different volumes.
"""

FAKE_CLAIMS = [
    # ── C01 — 12 farms, 64.0 ha, head to tail ──
    {"farm_id": "F012", "source_id": "C01", "distance_from_head_m": 119, "farmer_name": "Perumal", "crop": "sugarcane", "stage": "mid", "ky_stage": "flowering", "area_m2": 82000, "water_required_L": 2050000, "survival_minimum_L": 1025000, "ky": 0.5, "expected_yield_kg": 574000, "food_weight": 0.7, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.25, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 25.0, "net_mm": 25.0, "justification": "Sugarcane at flowering, Ky 0.50, needs 2,050,000 L over 4 days"},
    {"farm_id": "F013", "source_id": "C01", "distance_from_head_m": 240, "farmer_name": "Anitha", "crop": "paddy", "stage": "mid", "ky_stage": "flowering", "area_m2": 64000, "water_required_L": 1536000, "survival_minimum_L": 844800, "ky": 1.35, "expected_yield_kg": 32000, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.2, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 24.0, "net_mm": 24.0, "justification": "Paddy at flowering, Ky 1.35, needs 1,536,000 L over 4 days"},
    {"farm_id": "F014", "source_id": "C01", "distance_from_head_m": 428, "farmer_name": "Karthik", "crop": "cotton", "stage": "mid", "ky_stage": "flowering", "area_m2": 71000, "water_required_L": 1633000, "survival_minimum_L": 653200, "ky": 0.5, "expected_yield_kg": 17750, "food_weight": 0.75, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Cotton at flowering, Ky 0.50, needs 1,633,000 L over 4 days"},
    {"farm_id": "F015", "source_id": "C01", "distance_from_head_m": 518, "farmer_name": "Vasanthi", "crop": "paddy", "stage": "development", "ky_stage": "vegetative", "area_m2": 55000, "water_required_L": 1265000, "survival_minimum_L": 695750, "ky": 1.0, "expected_yield_kg": 27500, "food_weight": 1.2, "fairness_debt": 0.9, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Paddy at vegetative, Ky 1.00, needs 1,265,000 L over 4 days"},
    {"farm_id": "F016", "source_id": "C01", "distance_from_head_m": 645, "farmer_name": "Subramani", "crop": "sugarcane", "stage": "development", "ky_stage": "vegetative", "area_m2": 90000, "water_required_L": 1494000, "survival_minimum_L": 747000, "ky": 0.75, "expected_yield_kg": 630000, "food_weight": 0.7, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.83, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 16.6, "net_mm": 16.6, "justification": "Sugarcane at vegetative, Ky 0.75, needs 1,494,000 L over 4 days"},
    {"farm_id": "F017", "source_id": "C01", "distance_from_head_m": 759, "farmer_name": "Meena", "crop": "maize", "stage": "late", "ky_stage": "ripening", "area_m2": 38000, "water_required_L": 456000, "survival_minimum_L": 205200, "ky": 0.2, "expected_yield_kg": 22800, "food_weight": 1.1, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.6, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 12.0, "net_mm": 12.0, "justification": "Maize at ripening, Ky 0.20, needs 456,000 L over 4 days"},
    {"farm_id": "F018", "source_id": "C01", "distance_from_head_m": 937, "farmer_name": "Dhanapal", "crop": "tomato", "stage": "mid", "ky_stage": "flowering", "area_m2": 26000, "water_required_L": 598000, "survival_minimum_L": 299000, "ky": 1.1, "expected_yield_kg": 52000, "food_weight": 1.0, "fairness_debt": 0.6, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Tomato at flowering, Ky 1.10, needs 598,000 L over 4 days"},
    {"farm_id": "F019", "source_id": "C01", "distance_from_head_m": 1078, "farmer_name": "Kalaivani", "crop": "groundnut", "stage": "mid", "ky_stage": "flowering", "area_m2": 31000, "water_required_L": 713000, "survival_minimum_L": 285200, "ky": 0.8, "expected_yield_kg": 6200, "food_weight": 0.95, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Groundnut at flowering, Ky 0.80, needs 713,000 L over 4 days"},
    {"farm_id": "F020", "source_id": "C01", "distance_from_head_m": 1170, "farmer_name": "Ravichandran", "crop": "paddy", "stage": "late", "ky_stage": "ripening", "area_m2": 58000, "water_required_L": 1044000, "survival_minimum_L": 574200, "ky": 0.2, "expected_yield_kg": 29000, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.9, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 18.0, "net_mm": 18.0, "justification": "Paddy at ripening, Ky 0.20, needs 1,044,000 L over 4 days"},
    {"farm_id": "F021", "source_id": "C01", "distance_from_head_m": 1333, "farmer_name": "Amudha", "crop": "sunflower", "stage": "mid", "ky_stage": "flowering", "area_m2": 44000, "water_required_L": 1012000, "survival_minimum_L": 404800, "ky": 1.0, "expected_yield_kg": 6600, "food_weight": 0.9, "fairness_debt": 1.1, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Sunflower at flowering, Ky 1.00, needs 1,012,000 L over 4 days"},
    {"farm_id": "F022", "source_id": "C01", "distance_from_head_m": 1419, "farmer_name": "Nagarajan", "crop": "cotton", "stage": "development", "ky_stage": "vegetative", "area_m2": 67000, "water_required_L": 1005000, "survival_minimum_L": 402000, "ky": 0.2, "expected_yield_kg": 16750, "food_weight": 0.75, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.75, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 15.0, "net_mm": 15.0, "justification": "Cotton at vegetative, Ky 0.20, needs 1,005,000 L over 4 days"},
    {"farm_id": "F023", "source_id": "C01", "distance_from_head_m": 1582, "farmer_name": "Sundari", "crop": "ragi", "stage": "mid", "ky_stage": "flowering", "area_m2": 14000, "water_required_L": 280000, "survival_minimum_L": 98000, "ky": 0.9, "expected_yield_kg": 3500, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.0, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 20.0, "net_mm": 20.0, "justification": "Ragi at flowering, Ky 0.90, needs 280,000 L over 4 days"},

    # ── C02 — 9 farms, 37.2 ha, head to tail ──
    {"farm_id": "F024", "source_id": "C02", "distance_from_head_m": 121, "farmer_name": "Elango", "crop": "paddy", "stage": "mid", "ky_stage": "flowering", "area_m2": 62000, "water_required_L": 1488000, "survival_minimum_L": 818400, "ky": 1.35, "expected_yield_kg": 31000, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.2, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 24.0, "net_mm": 24.0, "justification": "Paddy at flowering, Ky 1.35, needs 1,488,000 L over 4 days"},
    {"farm_id": "F025", "source_id": "C02", "distance_from_head_m": 293, "farmer_name": "Poongodi", "crop": "sugarcane", "stage": "mid", "ky_stage": "flowering", "area_m2": 74000, "water_required_L": 1850000, "survival_minimum_L": 925000, "ky": 0.5, "expected_yield_kg": 518000, "food_weight": 0.7, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.25, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 25.0, "net_mm": 25.0, "justification": "Sugarcane at flowering, Ky 0.50, needs 1,850,000 L over 4 days"},
    {"farm_id": "F026", "source_id": "C02", "distance_from_head_m": 362, "farmer_name": "Chandran", "crop": "maize", "stage": "mid", "ky_stage": "flowering", "area_m2": 41000, "water_required_L": 984000, "survival_minimum_L": 442800, "ky": 1.5, "expected_yield_kg": 24600, "food_weight": 1.1, "fairness_debt": 0.7, "is_smallholder": False, "cycle_days": 4, "kc": 1.2, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 24.0, "net_mm": 24.0, "justification": "Maize at flowering, Ky 1.50, needs 984,000 L over 4 days"},
    {"farm_id": "F027", "source_id": "C02", "distance_from_head_m": 493, "farmer_name": "Vijaya", "crop": "onion", "stage": "mid", "ky_stage": "flowering", "area_m2": 29000, "water_required_L": 609000, "survival_minimum_L": 274050, "ky": 0.8, "expected_yield_kg": 43500, "food_weight": 0.9, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 1.05, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 21.0, "net_mm": 21.0, "justification": "Onion at flowering, Ky 0.80, needs 609,000 L over 4 days"},
    {"farm_id": "F028", "source_id": "C02", "distance_from_head_m": 651, "farmer_name": "Arumugam", "crop": "groundnut", "stage": "development", "ky_stage": "vegetative", "area_m2": 36000, "water_required_L": 561600, "survival_minimum_L": 224640, "ky": 0.2, "expected_yield_kg": 7200, "food_weight": 0.95, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.78, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 15.6, "net_mm": 15.6, "justification": "Groundnut at vegetative, Ky 0.20, needs 561,600 L over 4 days"},
    {"farm_id": "F029", "source_id": "C02", "distance_from_head_m": 797, "farmer_name": "Malathi", "crop": "bean", "stage": "mid", "ky_stage": "flowering", "area_m2": 22000, "water_required_L": 506000, "survival_minimum_L": 227700, "ky": 1.1, "expected_yield_kg": 2200, "food_weight": 1.15, "fairness_debt": 1.3, "is_smallholder": False, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Bean at flowering, Ky 1.10, needs 506,000 L over 4 days"},
    {"farm_id": "F030", "source_id": "C02", "distance_from_head_m": 922, "farmer_name": "Sekar", "crop": "cotton", "stage": "late", "ky_stage": "ripening", "area_m2": 48000, "water_required_L": 672000, "survival_minimum_L": 268800, "ky": 0.25, "expected_yield_kg": 12000, "food_weight": 0.75, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.7, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 14.0, "net_mm": 14.0, "justification": "Cotton at ripening, Ky 0.25, needs 672,000 L over 4 days"},
    {"farm_id": "F031", "source_id": "C02", "distance_from_head_m": 1056, "farmer_name": "Jothi", "crop": "sorghum", "stage": "development", "ky_stage": "vegetative", "area_m2": 33000, "water_required_L": 448800, "survival_minimum_L": 157080, "ky": 0.29, "expected_yield_kg": 9900, "food_weight": 1.15, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.68, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 13.6, "net_mm": 13.6, "justification": "Sorghum at vegetative, Ky 0.29, needs 448,800 L over 4 days"},
    {"farm_id": "F032", "source_id": "C02", "distance_from_head_m": 1143, "farmer_name": "Kumaresan", "crop": "tomato", "stage": "development", "ky_stage": "vegetative", "area_m2": 27000, "water_required_L": 475200, "survival_minimum_L": 237600, "ky": 0.4, "expected_yield_kg": 54000, "food_weight": 1.0, "fairness_debt": 0.0, "is_smallholder": False, "cycle_days": 4, "kc": 0.88, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 17.6, "net_mm": 17.6, "justification": "Tomato at vegetative, Ky 0.40, needs 475,200 L over 4 days"},

    # ── T01 — 4 farms, 3.5 ha, head to tail ──
    {"farm_id": "F001", "source_id": "T01", "distance_from_head_m": 73, "farmer_name": "Murugan", "crop": "tomato", "stage": "mid", "ky_stage": "flowering", "area_m2": 10117, "water_required_L": 232691, "survival_minimum_L": 116346, "ky": 1.1, "expected_yield_kg": 20234, "food_weight": 1.0, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Tomato at flowering, Ky 1.10, needs 232,691 L over 4 days"},
    {"farm_id": "F002", "source_id": "T01", "distance_from_head_m": 178, "farmer_name": "Kavitha", "crop": "onion", "stage": "late", "ky_stage": "ripening", "area_m2": 8000, "water_required_L": 120000, "survival_minimum_L": 54000, "ky": 0.3, "expected_yield_kg": 12000, "food_weight": 0.9, "fairness_debt": 1.2, "is_smallholder": True, "cycle_days": 4, "kc": 0.75, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 15.0, "net_mm": 15.0, "justification": "Onion at ripening, Ky 0.30, needs 120,000 L over 4 days"},
    {"farm_id": "F003", "source_id": "T01", "distance_from_head_m": 247, "farmer_name": "Rajesh", "crop": "ragi", "stage": "development", "ky_stage": "vegetative", "area_m2": 5000, "water_required_L": 65000, "survival_minimum_L": 22750, "ky": 0.3, "expected_yield_kg": 1250, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 0.65, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 13.0, "net_mm": 13.0, "justification": "Ragi at vegetative, Ky 0.30, needs 65,000 L over 4 days"},
    {"farm_id": "F004", "source_id": "T01", "distance_from_head_m": 336, "farmer_name": "Lakshmi", "crop": "paddy", "stage": "mid", "ky_stage": "flowering", "area_m2": 12000, "water_required_L": 288000, "survival_minimum_L": 158400, "ky": 1.35, "expected_yield_kg": 6000, "food_weight": 1.2, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.2, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 24.0, "net_mm": 24.0, "justification": "Paddy at flowering, Ky 1.35, needs 288,000 L over 4 days"},

    # ── T02 — 7 farms, 10.0 ha, head to tail ──
    {"farm_id": "F005", "source_id": "T02", "distance_from_head_m": 72, "farmer_name": "Selvam", "crop": "groundnut", "stage": "mid", "ky_stage": "flowering", "area_m2": 14000, "water_required_L": 322000, "survival_minimum_L": 128800, "ky": 0.8, "expected_yield_kg": 2800, "food_weight": 0.95, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.15, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 23.0, "net_mm": 23.0, "justification": "Groundnut at flowering, Ky 0.80, needs 322,000 L over 4 days"},
    {"farm_id": "F006", "source_id": "T02", "distance_from_head_m": 170, "farmer_name": "Bhavani", "crop": "ragi", "stage": "initial", "ky_stage": "vegetative", "area_m2": 9500, "water_required_L": 57000, "survival_minimum_L": 19950, "ky": 0.3, "expected_yield_kg": 2375, "food_weight": 1.2, "fairness_debt": 0.8, "is_smallholder": True, "cycle_days": 4, "kc": 0.3, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 6.0, "net_mm": 6.0, "justification": "Ragi at vegetative, Ky 0.30, needs 57,000 L over 4 days"},
    {"farm_id": "F007", "source_id": "T02", "distance_from_head_m": 265, "farmer_name": "Manikandan", "crop": "maize", "stage": "mid", "ky_stage": "flowering", "area_m2": 18000, "water_required_L": 432000, "survival_minimum_L": 194400, "ky": 1.5, "expected_yield_kg": 10800, "food_weight": 1.1, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.2, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 24.0, "net_mm": 24.0, "justification": "Maize at flowering, Ky 1.50, needs 432,000 L over 4 days"},
    {"farm_id": "F008", "source_id": "T02", "distance_from_head_m": 321, "farmer_name": "Saroja", "crop": "onion", "stage": "development", "ky_stage": "vegetative", "area_m2": 11000, "water_required_L": 193600, "survival_minimum_L": 87120, "ky": 0.45, "expected_yield_kg": 16500, "food_weight": 0.9, "fairness_debt": 1.5, "is_smallholder": True, "cycle_days": 4, "kc": 0.88, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 17.6, "net_mm": 17.6, "justification": "Onion at vegetative, Ky 0.45, needs 193,600 L over 4 days"},
    {"farm_id": "F009", "source_id": "T02", "distance_from_head_m": 420, "farmer_name": "Velu", "crop": "sorghum", "stage": "mid", "ky_stage": "flowering", "area_m2": 16500, "water_required_L": 346500, "survival_minimum_L": 121275, "ky": 1.08, "expected_yield_kg": 4950, "food_weight": 1.15, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 1.05, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 21.0, "net_mm": 21.0, "justification": "Sorghum at flowering, Ky 1.08, needs 346,500 L over 4 days"},
    {"farm_id": "F010", "source_id": "T02", "distance_from_head_m": 504, "farmer_name": "Shanthi", "crop": "bean", "stage": "development", "ky_stage": "vegetative", "area_m2": 12000, "water_required_L": 187200, "survival_minimum_L": 84240, "ky": 0.2, "expected_yield_kg": 1200, "food_weight": 1.15, "fairness_debt": 0.0, "is_smallholder": True, "cycle_days": 4, "kc": 0.78, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 15.6, "net_mm": 15.6, "justification": "Bean at vegetative, Ky 0.20, needs 187,200 L over 4 days"},
    {"farm_id": "F011", "source_id": "T02", "distance_from_head_m": 560, "farmer_name": "Ganesan", "crop": "paddy", "stage": "initial", "ky_stage": "vegetative", "area_m2": 19000, "water_required_L": 418000, "survival_minimum_L": 229900, "ky": 1.0, "expected_yield_kg": 9500, "food_weight": 1.2, "fairness_debt": 0.4, "is_smallholder": True, "cycle_days": 4, "kc": 1.1, "eto_used": 5.0, "effective_rain_mm": 0.0, "gross_mm": 22.0, "net_mm": 22.0, "justification": "Paddy at vegetative, Ky 1.00, needs 418,000 L over 4 days"},
]

# Allocation always runs against ONE command area, so group them.
CLAIMS_BY_SOURCE = {}
for _c in FAKE_CLAIMS:
    CLAIMS_BY_SOURCE.setdefault(_c["source_id"], []).append(_c)


if __name__ == "__main__":
    # Drift check. Regenerate if this reports STALE.
    #
    # Compares BY FARM ID, not by position. This file is grouped by
    # source for readability, while the engine returns demo order, so a
    # positional zip would compare F001 against F012 and report every
    # row as stale when nothing had actually changed.
    from generate import demo_farms
    from farm_agent import build_claims
    from constants import WEATHER_STATES

    live = {c["farm_id"]: c for c in
            build_claims(demo_farms(), WEATHER_STATES["normal"])}
    stored = {c["farm_id"]: c for c in FAKE_CLAIMS}

    missing = sorted(set(live) - set(stored))
    extra = sorted(set(stored) - set(live))
    drift = sorted(f for f in set(live) & set(stored) if live[f] != stored[f])

    if missing or extra or drift:
        if missing:
            print("STALE — engine has farms this file lacks:", missing)
        if extra:
            print("STALE — this file has farms the engine lacks:", extra)
        if drift:
            print("STALE — values changed for:", drift)
            for f in drift:
                for k in sorted(live[f]):
                    if live[f][k] != stored[f].get(k):
                        print(f"    {f}.{k}: {stored[f].get(k)!r} "
                              f"-> {live[f][k]!r}")
        print()
        print("Regenerate: copy the dicts below over FAKE_CLAIMS.")
        print()
        for c in live.values():
            print(c)
    else:
        print(f"fake_claims.py matches the engine exactly — "
              f"{len(FAKE_CLAIMS)} claims across "
              f"{len(CLAIMS_BY_SOURCE)} sources "
              f"({', '.join(f'{k}:{len(v)}' for k, v in sorted(CLAIMS_BY_SOURCE.items()))}).")